# Generated by Django 5.1.4 on 2024-12-07 15:56

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataFileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_name', models.CharField(max_length=255)),
                ('size', models.PositiveIntegerField()),
                ('time_upload', models.DateTimeField(default=django.utils.timezone.now)),
                ('expire_time', models.DateTimeField(default=datetime.datetime(2025, 1, 6, 15, 56, 54, 69562, tzinfo=datetime.timezone.utc))),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='HRFCodeFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hrf_code', models.CharField(max_length=20, unique=True)),
                ('facility_name', models.CharField(max_length=255)),
            ],
        ),
    ]
