# Generated by Django 5.1.4 on 2024-12-07 16:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datafileupload',
            name='expire_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 6, 16, 0, 58, 701882, tzinfo=datetime.timezone.utc)),
        ),
    ]
