# Generated by Django 5.1.4 on 2024-12-21 09:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0003_alter_datafileupload_expire_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='EncryptedDataModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_data', models.BinaryField()),
            ],
        ),
        migrations.AlterField(
            model_name='datafileupload',
            name='expire_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 20, 9, 16, 16, 72735, tzinfo=datetime.timezone.utc)),
        ),
    ]
