# Generated by Django 5.1.4 on 2024-12-21 17:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0004_encrypteddatamodel_alter_datafileupload_expire_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datafileupload',
            name='expire_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 20, 17, 58, 36, 419923, tzinfo=datetime.timezone.utc)),
        ),
    ]
