# Generated by Django 5.1.4 on 2024-12-22 04:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0005_alter_datafileupload_expire_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacilityEncryptedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_name', models.CharField(max_length=255)),
                ('encrypted_file', models.FileField(upload_to='encrypted_data/')),
                ('encryption_key', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='EncryptedDataModel',
        ),
        migrations.AlterField(
            model_name='datafileupload',
            name='expire_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 21, 4, 17, 56, 757717, tzinfo=datetime.timezone.utc)),
        ),
    ]
