# Generated by Django 5.1.4 on 2024-12-22 18:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0006_facilityencrypteddata_delete_encrypteddatamodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilityencrypteddata',
            name='facility_biom',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='datafileupload',
            name='expire_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 21, 18, 23, 32, 528835, tzinfo=datetime.timezone.utc)),
        ),
    ]
