# Generated by Django 5.1.4 on 2024-12-23 05:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0007_facilityencrypteddata_facility_biom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datafileupload',
            name='expire_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 22, 5, 24, 45, 429551, tzinfo=datetime.timezone.utc)),
        ),
    ]
